name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Download Reference Doc
        run:  |
          curl https://codeload.github.com/ClickHouse/ClickHouse/tar.gz/master | tar -xz -C ./ --strip=2 "ClickHouse-master/docs/"
          cp ./en/sql-reference/syntax.md docs/
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Install and build Docusaurus website
      - name: Build Docusaurus website
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm install -g yarn
          yarn install
          yarn build --out-dir .vercel/output
      - name: Create vercel metadata files
        shell: bash
        run: |
          cat > .vercel/output/config.json << EOF
          {
            "version": 3,
            "routes": [
              {
                "src": "^/[^./]+\\.[0-9a-f]{8}\\.(css|js)$",
                "headers": {
                  "cache-control": "max-age=31536000, immutable"
                },
                "continue": true
              },
              {
                "src": "^/assets/images/[^/]+-[0-9a-f]{32}\\.(ico|svg|jpg|jpeg|png|gif|webp)$",
                "headers": {
                  "cache-control": "max-age=31536000, immutable"
                },
                "continue": true
              },
              {
                "src": "^/assets/medias/[^/]+-[0-9a-f]{32}\\.(ogv|wav|mp3|m4a|aac|oga|flac)$",
                "headers": {
                  "cache-control": "max-age=31536000, immutable"
                },
                "continue": true
              },
              {
                "src": "^/assets/files/[^/]+-[0-9a-f]{32}\\.(pdf|doc|docx|xls|xlsx|zip|rar)$",
                "headers": {
                  "cache-control": "max-age=31536000, immutable"
                },
                "continue": true
              },
              {
                "src": "^/ideal-img/[^/]+\\.[0-9a-f]{7}\\.\\d+\\.(png|jpe?g|gif)$",
                "headers": {
                  "cache-control": "max-age=31536000, immutable"
                },
                "continue": true
              },
              {
                "handle": "error"
              },
              {
                "status": 404,
                "src": "^(?!/api).*$",
                "dest": "/404.html"
              },
              {
                "handle": "filesystem"
              },
              {
                "src": ".*",
                "status": 404,
                "dest": "404.html"
              }
            ],
            "framework": {
              "version": "2.4.0"
            },
            "crons": []
          }
          EOF
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --debug
